### PR TITLE
Fix maybeLogin() logic

### PR DESCRIPTION
**Pull request by brugidou**
Only login if a password is provided

### CODE REVIEW

**Comment by kolencherry** [comment]
@michaelneale, @butlermh Could you possibly merge this PR? 60a7fe9 broke the functionality of being able to login to registries.

**Comment by butlermh** [comment]
Oops - yes sorry my fault - I [changed](https://github.com/jenkinsci/docker-build-publish-plugin/blob/master/src/main/java/com/cloudbees/dockerpublish/DockerBuilder.java#L213) the [logic](https://github.com/jenkinsci/docker-build-publish-plugin/blob/50ed4a39ddfa47db9e206f2e34b139a6a06deb10/src/main/java/com/cloudbees/dockerpublish/DockerBuilder.java#L139) adding [defined](https://github.com/jenkinsci/docker-build-publish-plugin/blob/master/src/main/java/com/cloudbees/dockerpublish/DockerBuilder.java#L74) - now it needs a not. 

Unfortunately I don't have permissions to do the merge - @michaelneale  and I discussed it but it never happened.

**Comment by michaelneale** [comment]
Looking at it now.

**Comment by butlermh** [comment]
Sorry Michael, this is my fault - hopefully the links will help.

**Comment by michaelneale** [comment]
OK doing the release now - thanks for this. @butlermh I will get you commit access to this repo if you like (I have to work out how to drive the irc bot).

**Comment by kolencherry** [comment]
Thanks guys! Appreciate it. :+1:

**Comment by michaelneale** [comment]
OK released - should be in all good records stores (maven repos) near you soon. 

Thanks everyone for your help.

**Pull request merged**
