### PR TITLE
Proposed fix for JENKINS-25689 - Version 3

### PR DESCRIPTION
**Pull request by butlermh**
Here is the new, better PR for fixing Jenkins-25689. It's a replacement for #7 and #6. It's better because

- it automatically adds the latest tag
- it allows multiple tags, separated by commas
- instead of rebuilding the image for each tag, it builds it once, determines the image hash, then uses that to tag the image.

So much better than the previous version.

I have tested it on our local Jenkins instance.

### CODE REVIEW

**Comment by edmundcraske** [comment]
This doesn't seem to work properly for me on CentOS 6.6 and docker-io package from EPEL (version 1.4.1-3.el6) - for some reason although it builds a docker image with the specified tag (in this case, $BUILD_NUMBER) successfully, it then goes and does a new build with tag latest, rather than just tagging, and ends up building a new image with a different ID, rather than ending up with latest pointing at the same image. I'm not sure what I can do to work out why it's going wrong, but the build output does contain e.g. 'Successfully built 8c27b2288fd7' which should match the regex in the code, so I don't get why it doesn't work?

**Comment by edmundcraske** [comment]
Have just replaced my docker binary with the one listed at https://docs.docker.com/installation/binaries/ (i.e. 1.5.0 latest) and it still performs the same way - seems to me that the regex matching doesn't work properly for some reason but I'm not sure why...

Having looked more closely, the 'latest' tag is at least ending up with the same ID after building as the numbered tag, so it's not as wasteful as I thought, but it should still realise that it can just tag...

**Comment by butlermh** [comment]
Hi @edmundcraske I just took a look at this and spotted two obvious errors - see #15 - can you test this PR and report if this resolves your issue? Thanks :-)

**Comment by edmundcraske** [comment]
What do I need to do to test with this instead of the plugin that Jenkins installs? Do I need to compile it?

**Comment by butlermh** [comment]
@edumundcraske Yes you would check out PR, compile with Maven, then Jenkins has an option for manually updating jars from local copies, use that to load the fixed jar.

I am kinda busy at the moment but I just sent you a PM via LinkedIn (hope I had the right Edmund Craske) I can generate the jar for you if you send me your email but it would help me if you do the test. Thanks!

**Comment by butlermh** [comment]
@edmundcraske If you want to do it yourself - you will need Maven installed - 

        git clone git@github.com:butlermh/docker-build-publish-plugin.git
        cd docker-build-publish-plugin 
        git fetch origin attempt4
        git checkout attempt4
        mvn package

Then in Jenkins you need to install the plugin - Manage Jenkins > Manage Plugins > There is a tab called 'Advance configuration' and in that page there is an option to upload a plugin (select docker-build-publish-plugin.hpi in the target directory)

**Comment by edmundcraske** [comment]
Still doesn't seem to work, sadly - I'll try forking and tinkering and try to work out where it's going wrong... This isn't a blocker for me though so I might not find the time to look at it.

**Comment by butlermh** [comment]
It needs a proper test ... l guess this didn't work to begin with .. let me see if I can come up with one

**Comment by michaelneale** [comment]
You can also run direct from the checked out PR branch via: 

mvn hpi:run

- of course that will use a blank workspace and no extra plugins, but it will get you going with the current state of the PR. Hope that helps.

**Comment by edmundcraske** [comment]
Looks like we're just getting the object name of a PrintStream saved to the stdout String variable of the lastResult object, so it's not matching...

**Comment by edmundcraske** [comment]
I think that the executeCmd function needs to be looked at, I don't know how you're supposed to do this with Jenkins such that it will output your build output as normal but also allow you to parse it as a string?

**Comment by butlermh** [comment]
@edmundcraske It's probably [this line](https://github.com/jenkinsci/docker-build-publish-plugin/blob/master/src/main/java/com/cloudbees/dockerpublish/DockerBuilder.java#L257) then - looks like I had totally misunderstood the way the logger was working. I wrote [some code here](https://github.com/butlermh/docker-build-publish-plugin/commit/e5bd17e2262c3db23e2184c10a82212364752b01) but I am afraid I am still travelling can't test at the moment. Sorry - hopefully get to this tomorrow.

**Comment by edmundcraske** [comment]
@butlermh as commented on the PR I believe that this does fix the pattern matching so that the code works but it does break the scrolling output as the Launcher is no longer piping stdout to the logger. Unsure whether there is a neat way to split out the output so that we can pattern match on it whilst still logging it in real time?

**Comment by butlermh** [comment]
Thanks for the feedback @edmundcraske I guess we need something like the `tee` command in Unix - I coded something up. Please see whether it works? Thanks - sorry not to be able to test at the moment.

**Comment by edmundcraske** [comment]
Tagging is working with your 'tee' revision but logging output isn't working at all unfortunately!

**Pull request merged**
