### PR TITLE
Fixed IMAGE_BUILT_PATTERN

### PR DESCRIPTION
**Pull request by dbrgn**
In some cases, e.g. when installing something with `pip install` during the build process, the Regex would match the wrong line. Then the tagging (and thus the build) fails.

I fixed this by making the Regex match only hex strings longer than 12 characters, and by using the last match that has been found in stdout.

Test program:

```java
// test.java
import java.util.regex.Pattern;
import java.util.regex.Matcher;

class RegexTest {
    public static void main(String[] args) {
        Pattern pattern1 = Pattern.compile("Successfully built ([0-9a-f+])");
        Pattern pattern2 = Pattern.compile("Successfully built ([0-9a-f]{12,})");
        String stdout = 
            "Successfully built cssselect lxml Twisted\n" +
            "Successfully built 1e9f639afbd3\n" +
            "Successfully built 1e9f639afbd3104df6b58610f1d15ede92a72b351739242004849f4fa9cb9e87\n";
        Matcher m1 = pattern1.matcher(stdout);
        Matcher m2 = pattern2.matcher(stdout);

        String match1 = m1.find() ? m1.group(1) : "NONE";
        String match2 = "NONE";
        while (m2.find()) { match2 = m2.group(1); }

        System.out.println("Regex 1:");
        System.out.println("IN: " + pattern1);
        System.out.println("OUT: " + match1);
        System.out.println("---");
        System.out.println("Regex 2:");
        System.out.println("IN: " + pattern2);
        System.out.println("OUT: " + match2);
    }
}
```

Running it:

```
$ javac test.java && java RegexTest 
Regex 1:
IN: Successfully built ([0-9a-f+])
OUT: c
---
Regex 2:
IN: Successfully built ([0-9a-f]{12,})
OUT: 1e9f639afbd3104df6b58610f1d15ede92a72b351739242004849f4fa9cb9e87
```

And, [SCNR](http://regex.info/blog/2006-09-15/247):

> Some people, when confronted with a problem, think 
> “I know, I'll use regular expressions.”   Now they have two problems.
> -- Jamie Zawinski

:stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by carlossg** [comment]
thanks, can you add your  test as a junit test in https://github.com/jenkinsci/docker-build-publish-plugin/blob/master/src/test/java/com/cloudbees/dockerpublish/DockerBuilderTest.java#L62 ?

**Comment by dbrgn** [comment]
Yes. How can I run the tests from the command line? I just saw that there are no CI tests running on https://buildhive.cloudbees.com/job/jenkinsci/job/docker-build-publish-plugin/, so I assumed that there are none.

**Comment by carlossg** [comment]
`mvn test`

https://jenkins.ci.cloudbees.com/job/plugins/job/docker-build-publish-plugin/

**Comment by dbrgn** [comment]
Tests added.

**Comment by dbrgn** [comment]
Any news? :) @carlossg

**Comment by dbrgn** [comment]
When can we expect a release with this fix? :)

**Comment by carlossg** [comment]
now :) 1.0.1 released

**Comment by dbrgn** [comment]
yay, thanks! :sparkles:

**Pull request merged**
