### PR TITLE
correct the link to the wiki page for plugins and remove buildhive link

### PR DESCRIPTION
**Pull request by michaelneale**
@batmat @carlossg  how does this look? 

(regarding https://github.com/jenkinsci/docker-build-publish-plugin/commit/55f7fbf8094d5e65fbf78b1a52022159eb1cc3c5#commitcomment-15190609)

### CODE REVIEW

**Comment by michaelneale** [comment]
@reviewbybees

**Comment by andresrc** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
LGTM :bee:

**Comment by batmat** [comment]
Great, after next release [that line](https://github.com/jenkinsci/backend-update-center2/blob/master/src/main/resources/wiki-overrides.properties#L26) can then be removed. Thanks!

**Pull request merged**
