### PR TITLE
Fixing issue when Docker push returns result code 1 even though the p…

### PR DESCRIPTION
**Pull request by muthenberg**
…ush was successful. This seems to happen when there is nothing to push since the image on the server is equal to the local one. Still the build should not fail under these circumstances.

### CODE REVIEW

**Comment by carlossg** [comment]
I can't reproduce that problem with Docker 1.10.1

```
$ docker push csanchez/test; echo $?
The push refers to a repository [docker.io/csanchez/test]
16a7d371815d: Layer already exists
5f70bf18a086: Layer already exists
d0fca7ed04fa: Layer already exists
49cb696ba081: Layer already exists
a3f2e8b31ade: Layer already exists
0a12692e52ac: Layer already exists
ffcc1b742ae5: Layer already exists
b754180320cf: Layer already exists
b1054729675d: Layer already exists
9f03d39d6f5d: Layer already exists
ab78d3a9d26c: Layer already exists
12768f57423a: Layer already exists
2a99ce600abe: Layer already exists
65700858f210: Layer already exists
ee7816f09dfe: Layer already exists
f01e8626d61f: Layer already exists
b734b7339275: Layer already exists
65f3b0435c42: Layer already exists
latest: digest: sha256:67d3a0b1e476b187ea22e958c9a422c3cf8040a8f954610353b13daf91b6c786 size: 19530
0
```

**Comment by michaelneale** [comment]
@muthenberg is this still an issue? a merge with master will be required to try this out.

**Comment by muthenberg** [comment]
Hi,

It is still an issue for me. I am working with my own patched version of
the plugin and that runs perfectly. If no one else has that issue I
guess a merge is not necessary. I just wanted to provide my patch in
case there is a wider audience. Unfortunately I've got not much time to
check for different versions of docker. I am running docker version 1.10.1.

Regards
    Klemens

Am 08.03.2016 um 22:42 schrieb Michael Neale:

**Comment by carlossg** [comment]
I still see docker returning correctly the 0 exit code, and even if it weren't so, this patch only checks that the return code is 0 in a different way, so the behavior doesn't change

**Comment by muthenberg** [comment]
Hi,

Well ok. It works for me. If it is no issue for anyone else feel free to
ignore it. I just wanted to share my solution in case someone else could
use it.

Regards
    Klemens

Am 09.03.2016 um 11:02 schrieb Carlos Sanchez:

**Comment by michaelneale** [comment]
OK will close for now - feel free to re-open (will need to be remerged with master though, or rebased if you wish to proceed).

**Pull request closed without merging**
