### PR TITLE
Docker can now update the FROM image before building

### PR DESCRIPTION
**Pull request by jovandeginste**
Add the necessary flag to have --pull=true added if wanted

### CODE REVIEW

**Comment by michaelneale** [comment]
Any reason why this can't just be on all the time? there is a but of an explosion of config options happening at the moment - if anything can be a reasonable default would be nice. What is the downside of having it pull always? Would this surprise people?

**Comment by jovandeginste** [comment]
I implemented it in such a way that the default is "on"; however, Docker itself doens't pull by default. I'm not sure about the consequences in some cases, but OTOH perhaps it's not a bad thing to have many options (although perhaps in a more structured format as they explode)

**Comment by michaelneale** [comment]
ok fair enough - I could imagine there is a reason that docker cli doesn't default to pulling - so perhaps we should follow suit. Given we have to have this option - could you make the default to off, rather than on? Then I will merge and release.

**Comment by jovandeginste** [comment]
I'm not sure I agree - I implemented this specifically the other way around because I believe that is what most users will want, at least in a setup involving Jenkins. Obviously there are exceptions and that is why it's an option, but I imagine the bulk of the jobs will benefit from 'pull=true'.

**Comment by michaelneale** [comment]
hrm, fair point. I know official docker builds rebuild often from the base due to security fixes - so it is probably not a bad default - I am just sure some will complain.

**Comment by jovandeginste** [comment]
I have no idea how much work it would be to implement some Jenkins wide default setting (that can be overriden per individual job). Any thoughts?

**Comment by michaelneale** [comment]
not a huge amount - the login details are stored that way, but that may be over thinking it. Is this a global option people want with per project overrides? I think per project is fine with a sensible default.

**Comment by jovandeginste** [comment]
OK. Then I'll leave the decision to you. I implemented it that way, because first I did it the other way and realised I had to edit every job and 'flag the option'. I imagined that may well be the case for most other people and I then thought to be selfish about it :-)

So: your call?

**Comment by michaelneale** [comment]
Yep. I think might just do it - and see if people scream loudly.

**Comment by jovandeginste** [comment]
OK. If they do, we can either switch the meaning of the option or add a Jenkins-wide option.

**Comment by michaelneale** [comment]
OK on its way to a maven repo near you - thanks for this.

**Comment by zowers** [comment]
now docker 1.3.3 on debian fails flag provided but not defined: --pull

**Comment by michaelneale** [comment]
That is quite an old version of docker, would recommend using a recent one.

**Comment by zowers** [comment]
1. it is the version included in the debian sid linux distribution https://packages.debian.org/search?keywords=docker.io , 1.5 is currently in experimental only
2. it's the same used on amazon elastic beanstalk up until  March 23, 2015, see http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.docker
so its widely used

**Comment by zowers** [comment]
also, the checkbox No Force Pull in the job configuration gets cleared every time I open the configuration page

**Comment by michaelneale** [comment]
@jovandeginste what do you think of making the force pull off by default?

**Comment by jovandeginste** [comment]
I was thinking something like that; however, I'm wondering why the configuration gets cleared...? Any ideas on that?

**Comment by michaelneale** [comment]
@jovandeginste no - have you been able to reproduce? I don't have ready access to a computer right now

**Comment by jovandeginste** [comment]
I can reproduce indeed. Now to find out why...

**Comment by jovandeginste** [comment]
It may be to do with the '!' I used to invert. I now switched the code to invert everything (and default to not pulling). I'll add a pull request for this.

**Pull request merged**
