### PR TITLE
docker push should only push built tag

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by michaelneale** [comment]
This is causing some problems - I am tempted to undo this - can you explain why you needed this? when I tried - pushing a whole repo was efficient - it only pushes data that isn't already there anyway - it is basically a sync/rsync like experience. The ONLY reason to not push the repo and all tags is because you don't want some local tags to appear in the remote - is this the case?

**Comment by brycekahle** [comment]
What problems is it causing? Before it would push all the tags that I had tagged for that image before, which was far from efficient.

**Comment by michaelneale** [comment]
I assume you saw conversation on the other ticket (thanks for jumping in). 

Is there a case where you don't want it to push all those tags ? that is the case I am trying to understand specifically.

**Comment by brycekahle** [comment]
Yes. On every build I only want to push the new tag. The other tags have already been pushed to the registry. Pushing every tag was increasing my build times.

**Comment by michaelneale** [comment]
But it wouldn't push any new binary data with the tags - if they already there with the same hashes - it will just skip? 

Or was it the latency of the push that took too long as it had to check each tag?

**Comment by brycekahle** [comment]
There was no new data pushed, but there was still the added latency of 45 seconds while it checked the previous 5 tags (the number of preivous docker image builds I keep around on Jenkins).

**Comment by michaelneale** [comment]
hrm... that sounds like a bug with the client - it should have a more
efficient way - not sure if this should change the behaviour of build tools
so drastically for a docker "bug" (although it is annoying).

**Comment by brycekahle** [comment]
I disagree. It just spent the 45 seconds checking every layer of the 6 tags was on the registry. That takes time, especially if you have a lot of layers.

**Comment by michaelneale** [comment]
Not disagreeing that it takes time -
But the docker client should fix this, not all the tools around it.

**Comment by brycekahle** [comment]
I was disagreeing that it is a bug in the docker client. It is doing what it needs to. The performance of the network and registry is not something it controls. If you say `docker push repo/image` it will push all tags for `image`, thus why this PR.

I'm not sure where you think the bug in docker is.

**Comment by michaelneale** [comment]
It shouldn't be doing round trips for each layer - which I believe is the
source of the latency - it could do it efficiently in one request to
establish what is needed. I assume at the moment it is naively doing REST
calls for each tag to check if it has it - which adds up to a lot of
latency - not a bug, but poorly implemented enough for a mainstream that I
would call it a bug.

**Pull request merged**
