### PR TITLE
Add help text to builder section

### PR DESCRIPTION
**Pull request by carlossg**
and remove CloudBees from builder name as discussed in https://github.com/jenkinsci/docker-build-publish-plugin/pull/13#discussion-diff-27857334

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
:+1:

BTW I recommend creating PRs from branches in your own fork, rather than in the origin repo, mainly to work around a bug in the PR builder plugin, or at least for how we have it currently configured on this server. (Otherwise it runs one build for the PR, another for the origin branch, not noticing that they are the same revision.)

**Comment by carlossg** [comment]
Will do, thanks @jglick

**Comment by tfennelly** [comment]
:+1:

**Comment by daniel-beck** [comment]
> mainly to work around a bug in the PR builder plugin

@jglick Don't forget the Jira bot for anything saying `[FIXED]`, already resolving issues when the PR has just been created.

**Comment by jglick** [comment]
> already resolving issues when the PR has just been created

Right, forgot about that!

**Comment by michaelneale** [comment]
OK I have merged and pushed, but not released as my current network connection is so bad I don't trust to release it from here.

**Pull request merged**
