### PR TITLE
Invert the 'pull' switch to default to off

### PR DESCRIPTION
**Pull request by jovandeginste**
Invert the behaviour of the 'pull' switch (and edit the labels to reflect this)

### CODE REVIEW

**Comment by washeck** [comment]
Are you sure the default should be not to pull the base image? We ran into some hard-to-debug issues before #10 was merged as everyone in our team expected that having FROM base-image:latest means we allways build from the latest version. Without the pull, you start your image from a random version of the base image depending on which Jenkins slave you job is built on.

**Comment by michaelneale** [comment]
@jovandeginste with this - did you fix the unsticky checkbox? 
Also - as pointed out by @washeck the pull is a good feature for security and fixes, would it be better to just put in the fix for unsticky checkbox

**Comment by jovandeginste** [comment]
Reversing the way the switch works fixed the unsticky box but the
implementation is different. I still don't know why it did not work
beforehand, so I'm open to suggestions... I'm suspecting I've been working
with Ruby too much and there is a logical difference here between Ruby and
Java...

Also, the global switch might solve some problems here too?

Met vriendelijke groet,
Jo Vandeginste
Op 6-apr.-2015 05:07 schreef "Michael Neale" <notifications@github.com>:

**Comment by michaelneale** [comment]
Actually I think this is ok - just having it "on" by default should satisfy. For most users, it will do the right thing, for users of older docker versions, they can disable that flag (docker is still a bit of a moving target so I think this compromise is ok for now) - I can do this later probably.

**Comment by jovandeginste** [comment]
So the previous implementation is preferred, but with a working flag? I can see if I can get it to work...

**Comment by michaelneale** [comment]
I think your current change is great - just on by default is all.

**Comment by jovandeginste** [comment]
@washeck - that is exactly why I decided to try and implement it. I was experimenting with the swarm plugin and a chain of build where ever tier of images depended on some previous tier and I realised that it was not really working as I expected.

**Comment by jovandeginste** [comment]
OK I have no idea now how to put it on by default - please show :-)

**Comment by michaelneale** [comment]
I will see if I can work it out.

**Comment by michaelneale** [comment]
OK I have modified this to default to pulling - but you can uncheck it per build step. I will release later with some other pending changes.

**Pull request merged**
