### PR TITLE
Proposed fix for JENKINS-25689

### PR DESCRIPTION
**Pull request by butlermh**
I am working with Jenkins, Docker and a local registry, but I have been encountering problems because when I try to pull images from the local registry I get errors like this:

    Pulling repository  myreg:5000/vpsi/cassandra
    time="2015-01-19T15:38:28Z" level="fatal" 
    msg="Tag latest not found in repository myreg:5000/vpsi/cassandra" 
    Unable to find image 'myreg:5000/vpsi/cassandra:latest' locally

After trying [some alternative solutions](https://github.com/butlermh/docker-build-publish-plugin/commit/30c8c75346209300c9ed5c4d9a6a5fbba8bcc3d8) that [did not work](https://github.com/jenkinsci/docker-build-publish-plugin/pull/6) I concluded the problem is [this change](https://github.com/jenkinsci/docker-build-publish-plugin/pull/3). Before the change it was pushing all the tags of a particular image (including latest), but after it only the explicit tag will be pushed, and not the latest tag hence causing the problem above.

My solution is to also push the latest version, although as requested in JENKINS-25689 I added a checkbox so that this is user configurable. Perhaps that is not necessary, the latest version should always be pushed by default? 

I have tested this version and it does resolve my problem.

### CODE REVIEW

**Comment by michaelneale** [comment]
Interesting - so I am confused - if you wanted to tag and push latest - wouldn't you just put in "latest" as the tag? 

were you building both latest and a tag?

**Comment by michaelneale** [comment]
Perhaps the solution is to make it optional to only push the specified tag? Can you describe what you would do on the command line, by hand?

**Comment by butlermh** [comment]
Hi Michael,

Err .. let's start with what the plugin currently does and the problem.. if I add a tag like VERSION_$BUILDVERSION then it does this:

       docker build -t myreg:5000/vpsi/vps-specs-api:VERSION_9 specs-api/target/docker
       docker push myreg:5000/vpsi/vps-specs-api:VERSION_9

so subsequently if I do 

       docker pull myreg:5000/vpsi/vps-specs-api

I get 

       Pulling repository myreg:5000/vpsi/cassandra
           time="2015-01-19T15:38:28Z" level="fatal" 
           msg="Tag latest not found in repository myreg:5000/vpsi/cassandra" 
           Unable to find image 'myreg:5000/vpsi/cassandra:latest' locally

I guess one way around this would be to use the plugin in twice, once to give it the version tag, the other time to give it the latest tag?

**Comment by butlermh** [comment]
As for at the command line, I am not sure. I only just switched to using a local registry, because we need to publish some private images. For the Docker hub everything just seemed to work, I never encountered the problem above, and I never had to tag anything as "latest" explicitly. So the behavior of the local registry seems to be different to Docker Hub but I can't find an explanation of that. So I am kind of confused why I need to do this ... but testing has shown this is necessary to get everything to work.

At the moment my modifications do this:

        docker build -t myreg:5000/vpsi/kairosdb:VERSION_9 kairos/target/docker
        docker build -t myreg:5000/vpsi/kairosdb:latest kairos/target/docker
        docker push myreg:5000/vpsi/kairosdb:VERSION_9
        docker push myreg:5000/vpsi/kairosdb:latest

Now looking at this SO [post](http://stackoverflow.com/questions/21928780/create-multiple-tag-docker-image) and this [post](http://stackoverflow.com/questions/22080706/how-to-create-named-and-latest-tag-in-docker) this could be done more quickly - the first command

        docker build -t myreg:5000/vpsi/kairosdb:VERSION_9 kairos/target/docker

returns

        Pushing tag for rev [b9f0b699387d]

so then you can call docker tag

        docker tag -f b9f0b699387d  myreg:5000/vpsi/kairosdb:latest

which avoids having to rebuild the image - yesterday in my rush to get this to work the easiest thing was to rebuild the image rather than read STDOUT to get the tag hash. Sorry! I think you still need to do the two pushes though - although obviously I would want to test as yesterday I went through many variations that I thought should work but didn't. The version here does work for me and solves my problem, even [if it is slightly inelegant](http://stackoverflow.com/questions/21928780/create-multiple-tag-docker-image#answer-26305542).

**Comment by butlermh** [comment]
Sorry had to update the code examples slightly .. they should make more sense now.

**Comment by michaelneale** [comment]
Any reason why we can't make it push latest as well by default? If there is
nothing to push it is close to a no op. This does sound like a local
registry bug.

Perhaps that other fix to only push the tag is wrong - you would think that
if you had local changes you want to push them. If there is no material
change than it should be a no op - otherwise a bug.

**Comment by butlermh** [comment]
I did think the other fix was ... well not wrong ... but was having unexpected consequences for local registries. That's because I had some local images I had already tagged as latest - so when I pushed them everything worked. But then when I made some more they didn't work - it was necessary to tag them explicitly. So yes this does point to at least a difference in behavior (feature or bug?) between local registries and Docker hub.

But yes after doing it I thought that pushing latest as the default would make more sense, it would be possible to change the logic there.

**Comment by michaelneale** [comment]
Maybe I was too merge trigger happy with other feature.

I am puzzles though - how does official registry work if you just push a
repo? I don't see why it would trigger a massive upload when bits haven't
changed. Perhaps there is a case where you don't want to keep local changes
for some reason? Sounds like an edge case.

I am inclined to undo that other fix - or perhaps we should make it have an
option to only push the one tag.

**Comment by butlermh** [comment]
I would like someone with more Docker knowledge to clarify - but I think the problem is when I push an image without a tag then it is tagged "latest" automatically. But if I add a tag then it gets that tag instead. So before when I was pushing manually I didn't notice the problem, but when I switched to the Jenkins plugin, I decided to add a version tag ... and that caused the problem.

Docker pull behavior did change recently according to [a Docker Registry issue](https://github.com/docker/docker-registry/issues/637)

**Comment by michaelneale** [comment]
Hrm, it seems there is conflicting information. I need to try the latest again to see what the behavior is, not in a changelog. 

On another note - am intersted in others having commit access to this - as I am not an active user of this plugin anymore - would be good to get someone who is to have commit access to merge PRs - interested?

**Comment by michaelneale** [comment]
I am inclined to go with this - the only better option I can think of is to just have push [repo] with out tags (doesn't seem right) or ask user for a list of tags to push when publishing (seems a step backwards?) A search yeilds me nothing on appropriate behavior, let me look around.

**Comment by michaelneale** [comment]
OK I confirmed that pushing just the repo name will push any tags with it, and do the right thing. So my proposal is to undo the change that made it only push the build tag - the correct thing is just to run plain old "docker push" - it is still ok to tag things as latest as well (latest is JUST A TAG anyway). 

Do you want to rework this PR to undo that "damage"?

**Comment by brycekahle** [comment]
I believe docker hub does some magic and maintains the `latest` tag even when using tags. I've never had that automatically update for me running a private registry. I think the better option here would be to allow multiple tags to be specified (comma separated perhaps?), and push all of those.

**Comment by butlermh** [comment]
@brycekahle Thanks for the input - that's helpful. Sorry because your PR has been getting a bit of bashing. I think actually the problem is me not understanding Docker fully. Sorry. Yes multiple tags would be useful and it's what [this PR is requesting](https://issues.jenkins-ci.org/browse/JENKINS-25689). 

@michaelneale Yes I could help with the plugin - although I don't know how active I will be as this is for my current contract. I will put together a revised PR today but unfortunately I will be offline next week.

**Comment by michaelneale** [comment]
been discussing with @brycekahle on the other thread that I think it should just run "push" all the time - as is a docker client "weakness" that makes pushing all tags so painfully slow even when there is no change. 

@butlermh what do you think? should we just do this PR - which pushes latest by default - and keep the "only push" tag behaviour as it is now? If so - will merge and release this today (I am leaning the other way but not strong enough to not go ahead with this).

**Comment by butlermh** [comment]
Hi afraid I am travelling at moment - back 29th - two options I) merge as
is 2) allow comma separated tags. I am happy to write version 2 when I am
back?

Also I think I want to do tagging without rebuilding current approach is
quick fix.

**Comment by michaelneale** [comment]
Ping @butlermh - you still think merge as is? would like to get a release out this week.

**Comment by butlermh** [comment]
Hi Michael
I will get the to this Friday UK time no computer at the moment.
You can merge if you want - we have this version on our build server - but
UI will change next version to support multiple tags, right?

**Comment by michaelneale** [comment]
I guess so, if you two think this is the way to go.

**Comment by butlermh** [comment]
I am working on this, I have a new PR that supports multiple tags, just in the process of testing - https://github.com/butlermh/docker-build-publish-plugin/tree/attempt3

**Comment by michaelneale** [comment]
Great stuff.

**Comment by butlermh** [comment]
I am closing this PR, it's been replaced by #8.

**Pull request closed without merging**
