### PR TITLE
[JENKINS-27970] Build doesn't fail even if docker build does

### PR DESCRIPTION
**Pull request by carlossg**
Fix the conditionals

### CODE REVIEW

**Comment by carlossg** [comment]
@reviewbybees

**Comment by oleg-nenashev** [comment]
:+1: for the change
A unit tests suite would be useful to cover such basic use-cases

**Comment by washeck** [comment]
Can you please make a bugfix release of the plugin? This is a critical issue for us and it seems like the new 1.0 release with docker-commons dependency will take some time so it makes sense to have bugfix 0.16 before releasing 1.0.

**Comment by carlossg** [comment]
Released 0.16

**Pull request merged**
