### PR TITLE
Update the plugin to docker-commons-1.0

### PR DESCRIPTION
**Pull request by oleg-nenashev**
docker-commons-1.0 has compatibility changes, so the plugin should be updated.

@reviewbybees @carlossg

### CODE REVIEW

**Comment by carlossg** [comment]
+1

**Comment by stephenc** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
@carlossg 
I want to release 1.0-beta with a patch. Would it be OK?

**Comment by carlossg** [comment]
sounds good to me

**Pull request merged**
