### PR TITLE
Candidate fix for the problem reported by Edmund Craske

### PR DESCRIPTION
**Pull request by butlermh**
@edmundcraske here is a candidate fix for the problem you reported can you test and see if this resolves the issue?

### CODE REVIEW

**Comment by michaelneale** [comment]
Is this at all related to? https://issues.jenkins-ci.org/browse/JENKINS-27920

**Comment by butlermh** [comment]
@michaelneale yes I hadn't seen the issue.

**Comment by carlossg** [comment]
I have fixed it in https://github.com/jenkinsci/docker-build-publish-plugin/commit/66574a0fa64c6f636a93911e66b24ec91e2573f3#diff-a7c45f7e2ba80619b5aad549aadc5ef3L225
as part of PR #17

**Comment by butlermh** [comment]
Thanks Carlos, great work on this! @edmundcraske and I have been working on [a similar fix here](https://github.com/butlermh/docker-build-publish-plugin/tree/attempt4) but it looks like you beat us too it. You have a test too which is better.

Two comments though - this is my mistake not yours but your code still has it - I think this line
       
       private static final Pattern IMAGE_BUILT_PATTERN = Pattern.compile(".*?Successfully built ([0-9a-z]*).*?");

should be

       private static final Pattern IMAGE_BUILT_PATTERN = Pattern.compile(".*?Successfully built ([0-9a-f]*).*?", , Pattern.DOTALL);

Because the tag ID is hex, right? And DOTALL will match newlines?

Thanks, very best!

**Comment by edmundcraske** [comment]
I'm happy that #17 achieves what this was intended to achieve, so this should be closed in favour of that.

**Comment by carlossg** [comment]
I'm taking your regex comments into #17

**Pull request closed without merging**
